import type { AppSettings } from '../types';

export const TEMPLATE_ASSISTANT_LABEL = 'Built-in Template Assistant (offline)';
export const TEMPLATE_ASSISTANT_NOTICE =
  'Built-in template assistant (offline): this is a reusable canned template, not a response generated by a language model. Configure a cloud or local model in Settings > AI for real generation.';

export interface AiTaskResult {
  content: string;
  explanation?: string;
  suggestedAction?: string;
}

export async function processAiRequest(
  task: string,
  context: string,
  settings?: AppSettings
): Promise<string> {
  const provider = settings?.aiProvider || 'local';

  if (provider === 'openai' && settings?.aiApiKey) {
    try {
      const res = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${settings.aiApiKey}`,
        },
        body: JSON.stringify({
          model: settings.aiModel || 'gpt-4o',
          temperature: settings.aiTemperature ?? 0.7,
          messages: [
            {
              role: 'system',
              content:
                'You are the AI assistant embedded in Simple Office Suite, a local office suite. Provide concise, professional office content in clean markdown or plain text as requested. Only the task and the content the user selected are sent to you.',
            },
            {
              role: 'user',
              content: `Task: ${task}\n\nContext/Input:\n${context}`,
            },
          ],
        }),
      });
      if (res.ok) {
        const data = await res.json();
        return data.choices?.[0]?.message?.content || 'No response generated.';
      }
    } catch (err) {
      console.warn('OpenAI request failed, falling back to the built-in template assistant:', err);
    }
  }

  if (provider === 'anthropic' && settings?.aiApiKey) {
    try {
      const res = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': settings.aiApiKey,
          'anthropic-version': '2023-06-01',
          'anthropic-dangerous-direct-browser-access': 'true',
        },
        body: JSON.stringify({
          model: settings.aiModel || 'claude-3-5-sonnet-20241022',
          max_tokens: 1500,
          temperature: settings.aiTemperature ?? 0.7,
          messages: [
            {
              role: 'user',
              content: `Task: ${task}\n\nContext:\n${context}`,
            },
          ],
        }),
      });
      if (res.ok) {
        const data = await res.json();
        return data.content?.[0]?.text || 'No response generated.';
      }
    } catch (err) {
      console.warn('Anthropic request failed, falling back to the built-in template assistant:', err);
    }
  }

  if (provider === 'ollama') {
    const url = settings?.aiApiKey || 'http://localhost:11434';
    try {
      const res = await fetch(`${url}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: settings?.aiModel || 'llama3.2',
          prompt: `Task: ${task}\n\nContext:\n${context}`,
          stream: false,
        }),
      });
      if (res.ok) {
        const data = await res.json();
        return data.response || 'No response generated.';
      }
    } catch (err) {
      console.warn('Ollama request failed, falling back to the built-in template assistant:', err);
    }
  }

  return runTemplateAssistant(task, context);
}

export function runTemplateAssistant(task: string, input: string): string {
  const cleanInput = input.trim();
  const lowerTask = task.toLowerCase();

  if (lowerTask.includes('reply') || lowerTask.includes('respond')) {
    if (lowerTask.includes('polite decline') || lowerTask.includes('decline')) {
      return `${TEMPLATE_ASSISTANT_NOTICE}\n\nDear sender,\n\nThank you for reaching out and sharing these details. After reviewing the request, we are not able to proceed at this time because of current commitments.\n\nThank you for your time and we wish you well with the project.\n\nBest regards,\nRiley Adams`;
    }
    if (lowerTask.includes('friendly') || lowerTask.includes('positive') || lowerTask.includes('accept')) {
      return `${TEMPLATE_ASSISTANT_NOTICE}\n\nHi,\n\nThanks for the update. The plan looks good and matches the goals for this quarter. I reviewed the milestones and agree with the proposed timeline.\n\nLet's set up a short sync early next week to confirm the remaining action items.\n\nWarm regards,\nRiley`;
    }
    if (lowerTask.includes('request info') || lowerTask.includes('clarif')) {
      return `${TEMPLATE_ASSISTANT_NOTICE}\n\nHello,\n\nThanks for your message. Before we continue, could you clarify two points about the scope and schedule?\n\n1. What is the target start date for phase one?\n2. Are there any prerequisites we need to prepare?\n\nLooking forward to your reply.\n\nSincerely,\nRiley`;
    }
    return `${TEMPLATE_ASSISTANT_NOTICE}\n\nHi,\n\nThanks for your message about "${cleanInput.slice(0, 40)}".\n\nI am reviewing the details now and will send complete feedback by the end of today.\n\nBest regards,\nRiley Adams`;
  }

  if (lowerTask.includes('summarize email') || lowerTask.includes('summary') || lowerTask.includes('summarize')) {
    return `${TEMPLATE_ASSISTANT_NOTICE}\n\n### Summary Template\n\n- **Topic**: ${cleanInput ? cleanInput.slice(0, 80) : 'Add the message or document text you want summarized.'}\n- **Key points**:\n  • Replace this line with the first main point.\n  • Replace this line with the second main point.\n  • Replace this line with supporting numbers or dates.\n- **Action items**:\n  1. Name an owner and a due date.\n  2. Confirm the next meeting or review.\n  3. Note anything that still needs confirmation.`;
  }

  if (lowerTask.includes('formula') || lowerTask.includes('sheet') || lowerTask.includes('excel')) {
    const formulaNote = `${TEMPLATE_ASSISTANT_NOTICE}\n\n`;
    if (lowerTask.includes('sum') || lowerTask.includes('total')) {
      return `${formulaNote}=SUM(B2:B20)\n\n*Adds the values in cells B2 through B20.*`;
    }
    if (lowerTask.includes('average') || lowerTask.includes('mean')) {
      return `${formulaNote}=AVERAGE(C2:C50)\n\n*Returns the mean of the range, ignoring empty cells.*`;
    }
    if (lowerTask.includes('vlookup') || lowerTask.includes('lookup') || lowerTask.includes('find')) {
      return `${formulaNote}=VLOOKUP(A2, Products!A1:D100, 3, FALSE)\n\n*Finds A2 in the first column of the table and returns the value from column 3.*`;
    }
    if (lowerTask.includes('condition') || lowerTask.includes('if')) {
      return `${formulaNote}=IF(D2>=10000, "Target Achieved", "In Progress")\n\n*Compares D2 with the threshold and returns one of two labels.*`;
    }
    return `${formulaNote}=SUMIF(A2:A50, "Completed", B2:B50)\n\n*Adds the values in column B where column A equals "Completed".*`;
  }

  if (lowerTask.includes('polish') || lowerTask.includes('grammar') || lowerTask.includes('rewrite')) {
    if (cleanInput.length > 0) {
      return cleanInput
        .replace(/\b(wanna|gonna)\b/gi, 'would like to')
        .replace(/\b(good)\b/gi, 'clear')
        .replace(/\b(very)\b/gi, 'significantly')
        .replace(/\b(fix)\b/gi, 'resolve');
    }
    return `${TEMPLATE_ASSISTANT_NOTICE}\n\nPaste the text you want rewritten, or use a configured model for real grammar correction.`;
  }

  if (lowerTask.includes('slide') || lowerTask.includes('presentation')) {
    return `${TEMPLATE_ASSISTANT_NOTICE}\n\n## Slide Outline Template\n\n- **Title slide**: topic and subtitle\n- **Where we are**: current status in one line\n- **What changed**: two or three short points\n- **What is next**: owners and dates\n- **Questions**: open items for the audience\n\n> Replace each bullet with your own content.`;
  }

  return `${TEMPLATE_ASSISTANT_NOTICE}\n\n### Drafting Template\n\n${cleanInput ? cleanInput + '\n\n' : ''}1. **Objective**: state the result you want.\n2. **Approach**: list the steps you will take.\n3. **Outcome**: describe what success looks like and how you will check it.`;
}
